/*
 * MIT License
 * Copyright (c) 2019 Francisco Grau
 */
package com.palmaactiva.jaminas.ui;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowEvent;
import javax.swing.JButton;

/**
 *
 * @author Fran Grau - fran@kydemy.com
 */
public class Ventana extends javax.swing.JFrame {

    private DialogoNuevoJuego dialogoNuevoJuego;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initApariencia();
        initComponents();
        initEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanelJuego = new javax.swing.JPanel();
        jPanelRegilla = new javax.swing.JPanel();
        jPanelEstado = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuGuardar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 455));
        setPreferredSize(new java.awt.Dimension(620, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(620, 440));

        jPanelJuego.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelRegillaLayout = new javax.swing.GroupLayout(jPanelRegilla);
        jPanelRegilla.setLayout(jPanelRegillaLayout);
        jPanelRegillaLayout.setHorizontalGroup(
            jPanelRegillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanelRegillaLayout.setVerticalGroup(
            jPanelRegillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        jPanelJuego.add(jPanelRegilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 24, -1, -1));

        javax.swing.GroupLayout jPanelEstadoLayout = new javax.swing.GroupLayout(jPanelEstado);
        jPanelEstado.setLayout(jPanelEstadoLayout);
        jPanelEstadoLayout.setHorizontalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanelEstadoLayout.setVerticalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNuevo.setText("Nuevo Juego...");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuNuevo);
        jMenuArchivo.add(jSeparator1);

        jMenuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuGuardar);
        jMenuArchivo.add(jSeparator2);

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuSalir);

        jMenuBar.add(jMenuArchivo);

        jMenu2.setText("Edit");
        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        this.dialogoNuevoJuego.setVisible(true);
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        this.salirJuego();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void initEventos() {
        this.addComponentListener(new ComponentAdapter() {
            public void componentShown(ComponentEvent e) {
                if (dialogoNuevoJuego == null) {
                    dialogoNuevoJuego = new DialogoNuevoJuego(Ventana.this, rootPaneCheckingEnabled);
                    dialogoNuevoJuego.setLocationRelativeTo(Ventana.this);
                    dialogoNuevoJuego.setVisible(true);
                }
            }
        });
    }

    private void initApariencia() {
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx = 0; idx < installedLookAndFeels.length; idx++) {
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JPanel jPanelJuego;
    private javax.swing.JPanel jPanelRegilla;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

    public void salirJuego() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    public void nuevaPartida(int filas, int columnas, int numMinas) {
        if (dialogoNuevoJuego != null) {
            dialogoNuevoJuego.dispose();
        }
        this.setVisible(false);
        int buttonSize = 30;

        jPanelRegilla.setLayout(new java.awt.GridLayout(filas, columnas, 0, 0));
        jPanelRegilla.setMaximumSize(new Dimension(filas * buttonSize, columnas * buttonSize));
        jPanelRegilla.setSize(filas * buttonSize, columnas * buttonSize);
        jPanelRegilla.setBounds(0, 0, filas * buttonSize, columnas * buttonSize);
        Dimension contentSize = new Dimension(600 + filas * buttonSize, 200 + columnas * buttonSize);
        this.setPreferredSize(contentSize);
        this.setMinimumSize(contentSize);
        this.setMaximumSize(contentSize);
        this.setSize(contentSize);
        setResizable(false);
        jPanelEstado.setSize(600, 200 + columnas * buttonSize);

        JButton botonJuego = null;
        for (int indiceFilas = 0; indiceFilas < filas; indiceFilas++) {
            for (int indiceColumnas = 0; indiceColumnas < columnas; indiceColumnas++) {
                botonJuego = new JButton();
                botonJuego.setSize(buttonSize, buttonSize);
                botonJuego.setMargin(new Insets(0, 0, 0, 0));
                botonJuego.setBorderPainted(false);
                jPanelRegilla.add(botonJuego);
            }
        }
        this.pack();
        setLocationRelativeTo(null);
        jPanelRegilla.updateUI();
        this.setVisible(true);
    }
}
